version: "3.8"
services:
    react-app:
        build: .
        ports:
            - "3000:3000"
        volumes: 
            - ./src:/app/src
    aws:
        image: amazon/aws-cli:latest
        volumes:
            - ~/.aws/credentials:/root/.aws/credentials
